language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.0'
  - '7.1'
  - nightly

branches:
    only:
        - master

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env:
        - COVERAGE='true'
        - COMPOSER_FLAGS='--prefer-lowest'

    - php: 'nightly'
      env:
        - DEV='true'

    # Symfony bridge - For specific versions
    - php: '7.0'
      env:
        - SYMFONY_VERSION='~3.1.0'
    - php: '7.0'
      env:
        - SYMFONY_VERSION='~3.2.0@dev'

    # Laravel bridge - For specific versions
    - php: '7.0'
      env:
        - LARAVEL_VERSION='~5.1.0'
    - php: '7.0'
      env:
        - LARAVEL_VERSION='~5.2.0'
    - php: '7.0'
      env:
        - LARAVEL_VERSION='~5.3.0'
    - php: '7.0'
      env:
        - LARAVEL_VERSION='~5.4.0@dev'

  allow_failures:
    - php: nightly
    - php: '7.0'
      env:
        - SYMFONY_VERSION='~3.2.0@dev'
    - php: '7.0'
      env:
        - LARAVEL_VERSION='~5.4.0@dev'

before_install:
  - set -eo pipefail
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - source bin/composer.sh
  - |
    if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then
        COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"
    fi

install:
  - composer update --prefer-dist $COMPOSER_FLAGS
  - source update_dependencies.sh
  - composer bin all update --prefer-dist $COMPOSER_FLAGS

script:
  - bin/tests.sh

notifications:
  email: false
